[package]
name = "accounting_spec"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
thiserror = "1.0.30"
rust_decimal = "1.17"
serde = { version = "1.0.130", features = ["derive"] }


